const products = [
    {
        _id: '1',
        name: 'Headphones',
        image:'/images/airpods.jpg',
        desciption: 'some description',
        brand:'Apple',
        category:'Electronics',
        price:'89.99',
        countInStock: 3,
        rating:4.5,
        numReviews:4,
    },
    {
        _id: '2',
        name: 'Headphones',
        image:'/images/airpods.jpg',
        desciption: 'some description',
        brand:'Apple',
        category:'Electronics',
        price:'89.99',
        countInStock: 3,
        rating:4.5,
        numReviews:4,
    },
    {
        _id: '3',
        name: 'Headphones',
        image:'/images/airpods.jpg',
        desciption: 'some description',
        brand:'Apple',
        category:'Electronics',
        price:'89.99',
        countInStock: 3,
        rating:4.5,
        numReviews:4,
    },
    {
        _id: '4',
        name: 'Headphones',
        image:'/images/airpods.jpg',
        desciption: 'some description',
        brand:'Apple',
        category:'Electronics',
        price:'89.99',
        countInStock: 3,
        rating:4.5,
        numReviews:4,
    },
];

export default products;